from tkinter import *
win = Tk()
win.geometry("400x400")
win.title("Entry 시용")
def change():
    txt1 = entry1.get() + entry2.get()
    label3.config(text = txt1)
def msg2():
    win.destroy()
    win.quit()
label1 = Label(win, text = "문자열 입력1 ")
label1.grid(row=0, column=0)
entry1 = Entry(win, width = 20, bg = "light green")
entry1.grid(row=0, column = 1)
label2 = Label(win, text = "문자열 입력2")
label2.grid(row=1, column=0)
entry2 = Entry(win, width = 20, bg = "light green")
entry2.grid(row=1, column=1)
button = Button(win, text = "클 릭", command = change)
button.grid(row=2, column=1)
button2 = Button(win, text = "종료", command = msg2)
button2.grid(row=3, column=1)
label3 = Label(win, text = "입력받은 문자열이 여기에 출력됩니다")
label3.grid(row=4, column=1)
win.mainloop()
